prixy:
    resource: "@PrixyBundle/Resources/config/routing.yml"
    prefix:   /
app:
    resource: "@AppBundle/Controller/"
    type:     annotation

oc_platform_translation:
    path:     /traduction/{name}
    defaults: { _controller: OCPlatformBundle:Advert:translation }