prixy:
    resource: "@PrixyBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    requirements:
        _locale: fr|en
app:
    resource: "@AppBundle/Controller/"
    type:     annotation

