<?php

namespace PrixyBundle\Repository;

/**
 * ligne_competenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ligne_competenceRepository extends \Doctrine\ORM\EntityRepository
{
}
