<?php

namespace PrixyBundle\Repository;

/**
 * objectifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class objectifRepository extends \Doctrine\ORM\EntityRepository
{
}
