<?php

namespace PrixyBundle\Repository;

/**
 * session_formationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class session_formationRepository extends \Doctrine\ORM\EntityRepository
{
}
