<?php

namespace PrixyBundle\Repository;

/**
 * themeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class themeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllAlphabetic(){
        return $this->findBy(array(), array('libelle'=> 'ASC'));
    }
}
